version: '3'
services:
  api:
    build: .
    container_name: api
    ports:
    - 4400:8000
    volumes:
    - ./:/app/
    entrypoint:
    - python
    - manage.py
    - runserver
    - 0.0.0.0:8000
    environment:
    - DJANGO_SETTINGS_MODULE=dm_api.settings.production
    - REDIS_DB=0
    - REDIS_HOST=redis
    depends_on:
    - redis
    networks:
    - internal
  redis:
    image: redis:5-buster
    container_name: redis
    networks:
    - internal
networks:
  internal:
    driver: bridge
